var DEFAULTS = { };
DEFAULTS['HGRAPH_WIDTH'] = 960;
DEFAULTS['HGRAPH_HEIGHT'] = 720;
DEFAULTS['HGRAPH_INNER_RADIUS'] = 120;
DEFAULTS['HGRAPH_OUTER_RADIUS'] = 200;

DEFAULTS['HGRAPH_APP_BOOTSTRAPS'] = ['data-hgraph-app','hgraph-app'];
DEFAULTS['HGRAPH_GRAPH_BOOTSTRAPS'] = ['data-hgraph-graph','hgraph-graph'];
DEFAULTS['HGRAPH_PAYLOAD_TRIGGERS'] = ['data-hgraph-payload','hgraph-payload'];
DEFAULTS['HGRAPH_RING_FILL_COLOR'] = '#97be8c';