var DEFAULTS = { };
DEFAULTS['HGRAPH_WIDTH'] = 960;
DEFAULTS['HGRAPH_HEIGHT'] = 720;
DEFAULTS['HGRAPH_RANGE_MINIMUM'] = 60;
DEFAULTS['HGRAPH_RANGE_MAXIMUM'] = 240;
DEFAULTS['HGRAPH_POINT_RADIUS'] = 10;
DEFAULTS['HGRAPH_SUBPOINT_RADIUS'] = 8;

DEFAULTS['HGRAPH_CANVAS_TEXTALIGN'] = 'center';
DEFAULTS['HGRAPH_CANVAS_TEXT'] = '24px Arial';
DEFAULTS['HGRAPH_POINT_COLOR_HEALTHY'] = '#616363';
DEFAULTS['HGRAPH_POINT_COLOR_UNHEALTHY'] = '#e1604f';
DEFAULTS['HGRAPH_APP_BOOTSTRAPS'] = ['[data-hgraph-app]','[hgraph-app]'];
DEFAULTS['HGRAPH_GRAPH_BOOTSTRAPS'] = ['[data-hgraph-graph]','[hgraph-graph]'];
DEFAULTS['HGRAPH_PAYLOAD_TRIGGERS'] = ['[data-hgraph-payload]','[hgraph-payload]'];
DEFAULTS['HGRAPH_RING_FILL_COLOR'] = '#97be8c';